In [7]:
import numpy as np
import pandas as pd
from fractions import Fraction

Week 6

In [90]:
# Odds
pie = 1/2
minus_pie = Fraction(pie-1)
odds = pie/minus_pie
print(odds)
print(Fraction(odds))


-1.0
-1


In [34]:
# Log odds
log_odds = np.log(pie/(1-pie))
print(log_odds)

0.28768207245178085


In [ ]:
w = [-ln(4), ln(2), -ln(5), ln(3)], where ln is the natural logarithm. It is applied to a patient's X-ray feature vector x = [1, 2, 1, 2]

In [93]:
# for binary logistic regression with ws and object x's what is probability the instance belongs to positive class 

w= np.array ([-np.log(4), np.log(2), -np.log(5), np.log(3)])
x = np.array([1, 2, 1, 2])

w_transpose_x = np.dot(w.T, x)
print("wtx")
print(w_transpose_x)

prob_object_in_pos_class = 1/(1+np.exp(-w_transpose_x))
print("prob object in poss class")
print(prob_object_in_pos_class)

wtx
0.5877866649021191
prob object in poss class
0.6428571428571428


Consider the fully connected neural network on slide 32 of Lecture 6. If we insert a new hidden layer with 12 neurons between the input layer (3 neurons) and the old hidden layer (4 neurons), with full connections between the input layer and new hidden layer, and full connections between new hidden layer and old hidden layer (no direct connections between the input layer and the old hidden layer). The same activation function sigma (sigmoid) is used in the new hidden layer.

How many learnable parameters in total are there for this two-hidden-layer neural network?

In [94]:
# Fully connect neural networks parameters 

number_of_inputs = 3
number_of_outputs = 2
no_neurons_in_first_hlayer = 12
no_neurons_in_second_hlayer = 4

weights = number_of_inputs*no_neurons_in_first_hlayer + no_neurons_in_first_hlayer*no_neurons_in_second_hlayer + no_neurons_in_second_hlayer*number_of_outputs
bias = (no_neurons_in_first_hlayer + no_neurons_in_second_hlayer + number_of_outputs)

print("no of weights")
print(weights)
print("bias")
print(bias)
print("Total parameters")
print(weights+bias)

no of weights
92
bias
18
Total parameters
110


In [87]:
# convolving function 
# remember to check if n size and stride and kernal size will work 

input_grid =np.array([[1,1,1,2,0],[0,1,1,1,0], [0,0,1,1,0],[0,0,1,1,0], [1,0,1,0,1]])
                      
kernel_grid = np.array([[2,0],[0,2]])


stride = 2
N_conv = len(input_grid)
F_conv = len(kernel_grid)

def convolving_function(input_grid, kernel_grid, N_conv, F_conv, stride):
    N_conv = len(input_grid)
    F_conv = len(kernel_grid)
    for i in list(range(int((N_conv-F_conv)/stride)+1)):
        for j in list(range(int((N_conv-F_conv)/stride)+1)):
            output_rm = np.sum(np.multiply(input_grid[(i*stride):F_conv+(i*stride),(j*stride):F_conv+(j*stride)], kernel_grid))
            print('\n row', i, 'col', j)
            print(output_rm)
            
convolving_function(input_grid, kernel_grid, N_conv, F_conv, stride)


 row 0 col 0
4

 row 0 col 1
4

 row 1 col 0
0

 row 1 col 1
4


Week 7

In [67]:
#convolving only for 5*5 matrix and stride 1 and 3*3 kernal 

input_grid =np.array([[1,1,1,0,0],[0,1,1,1,0], [0,0,1,1,1],[0,0,1,1,0], [0,1,1,0,0]])
print ("input grid")
print(input_grid)
                      
print("portion of the input grid we are looking at")
port = input_grid[0:3,0:3]
print(port)

kernel_grid = np.array([[0,1,0],[0,1,0],[0,1,0]])
print('\nKernel:')
print(kernel_grid)

stride = 1 
N_conv = len(input_grid)
F_conv = len(kernel_grid)

print("top_left")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("top_middle")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("top_right")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_left")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_middle")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_right")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_left")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_middle")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_right")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

input grid
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
portion of the input grid we are looking at
[[1 1 1]
 [0 1 1]
 [0 0 1]]

Kernel:
[[0 1 0]
 [0 1 0]
 [0 1 0]]
top_left

Output of sum of element wise multiplication of input portion and kernel:
2
top_middle

Output of sum of element wise multiplication of input portion and kernel:
3
top_right

Output of sum of element wise multiplication of input portion and kernel:
2
middle_left

Output of sum of element wise multiplication of input portion and kernel:
1
middle_middle

Output of sum of element wise multiplication of input portion and kernel:
3
middle_right

Output of sum of element wise multiplication of input portion and kernel:
3
bottom_left

Output of sum of element wise multiplication of input portion and kernel:
1
bottom_middle

Output of sum of element wise multiplication of input portion and kernel:
3
bottom_right

Output of sum of element wise multiplication of input portion and kernel:
2


In [84]:
#convolving only for 7*7 matrix and stride 2 and 3*3 kernal 

input_grid =np.array([[1,1,1,0,0,1,2],[0,1,1,1,0,1,2], [0,0,1,1,1,1,2],[0,0,1,1,0,1,2], [0,1,1,0,0,1,2],[0,1,1,0,0,1,2],[0,1,1,0,0,1,2]])
print ("input grid")
print(input_grid)
                      
print("portion of the input grid we are looking at")
port = input_grid[0:3,0:3]
print(port)

kernel_grid = np.array([[0,1,0],[0,1,0],[0,1,0]])
print('\nKernel:')
print(kernel_grid)

stride = 2
N_conv = len(input_grid)
F_conv = len(kernel_grid)

print("top_left")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("top_middle")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("top_right")
output_rm = np.sum(np.multiply(input_grid[0:F_conv,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_left")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_middle")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("middle_right")
output_rm = np.sum(np.multiply(input_grid[stride:F_conv+stride,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_left")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,0:F_conv], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_middle")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,stride:F_conv+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

print("bottom_right")
output_rm = np.sum(np.multiply(input_grid[stride+stride:F_conv+stride+stride,stride+stride:F_conv+stride+stride], kernel_grid))
print('\nOutput of sum of element wise multiplication of input portion and kernel:')
print(output_rm)

input grid
[[1 1 1 0 0 1 2]
 [0 1 1 1 0 1 2]
 [0 0 1 1 1 1 2]
 [0 0 1 1 0 1 2]
 [0 1 1 0 0 1 2]
 [0 1 1 0 0 1 2]
 [0 1 1 0 0 1 2]]
portion of the input grid we are looking at
[[1 1 1]
 [0 1 1]
 [0 0 1]]

Kernel:
[[0 1 0]
 [0 1 0]
 [0 1 0]]
top_left

Output of sum of element wise multiplication of input portion and kernel:
2
top_middle

Output of sum of element wise multiplication of input portion and kernel:
2
top_right

Output of sum of element wise multiplication of input portion and kernel:
3
middle_left

Output of sum of element wise multiplication of input portion and kernel:
1
middle_middle

Output of sum of element wise multiplication of input portion and kernel:
2
middle_right

Output of sum of element wise multiplication of input portion and kernel:
3
bottom_left

Output of sum of element wise multiplication of input portion and kernel:
3
bottom_middle

Output of sum of element wise multiplication of input portion and kernel:
0
bottom_right

Output of sum of element wise multi

In [85]:
# output size 

no_of_filters_1 = 1
N = 7
F = 3
stride_1 =2 

output_size = ((N-F)/stride_1) +1
print("size per filter")
print(output_size)
print("size for all filters")
print(output_size*no_of_filters_1)

size per filter
3.0
size for all filters
3.0


In [88]:
# number of parameters for a conv layer 

no_of_filters = 100
size_of_filter = 15*15*4
total_for_kernals = (size_of_filter+1)*no_of_filters
print("total parameters")
print(total_for_kernals)



total parameters
90100
